// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringService.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.roguesystems.edi.system.component;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContext;
import org.springframework.jdbc.core.JdbcTemplate;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

@ExtendWith(MockitoExtension.class)
public class SystemComponentServiceTest {

    @Mock
    private SystemComponentEntityDao systemComponentEntityDao;

    @Mock
    private SystemComponentEntityRepository systemComponentEntityRepository;

    @InjectMocks
    private SystemComponentService systemComponentService;

    @Test
    @DisplayName("Test Find By Id Success")
    public void testFindByIdSuccess() {
        
    }

    @Test
    @DisplayName("Test Find By Id Fail")
    public void testFindByIdFail() {
        
    }

    @Test
    @DisplayName("Test Save Success")
    public void testSaveSuccess() {
        
    }

    @Test
    @DisplayName("Test Save Fail")
    public void testSaveFail() {
        
    }

    @Test
    @DisplayName("Test Save System Component Null")
    public void testSaveSystemComponentNull() {
        
    }

    @Test
    @DisplayName("Test Save System Component Id Null")
    public void testSaveSystemComponentIdNull() {
        
    }

    @Test
    @DisplayName("Test Save System Component Edi System Null")
    public void testSaveSystemComponentEdiSystemNull() {
        
    }

    @Test
    @DisplayName("Test Save System Component Type Null")
    public void testSaveSystemComponentTypeNull() {
        
    }

    @Test
    @DisplayName("Test Save System Component Name Null")
    public void testSaveSystemComponentNameNull() {
        
    }

    @Test
    @DisplayName("Test Save System Component Identifier Null")
    public void testSaveSystemComponentIdentifierNull() {
        
    }

    @Test
    @DisplayName("Test Remove Success")
    public void testRemoveSuccess() {
        
    }

    @Test
    @DisplayName("Test Remove Fail")
    public void testRemoveFail() {
        
    }

    @Test
    @DisplayName("Test Search Success")
    public void testSearchSuccess() {
        
    }

    @Test
    @DisplayName("Test Search Fail")
    public void testSearchFail() {
        
    }

    @Test
    @DisplayName("Test Search Criteria Null")
    public void testSearchCriteriaNull() {
        
    }

    @Test
    @DisplayName("Test Get All Success")
    public void testGetAllSuccess() {
        
    }

    @Test
    @DisplayName("Test Get All Fail")
    public void testGetAllFail() {
        
    }

}