// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringService.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.roguesystems.edi.client;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContext;
import org.springframework.jdbc.core.JdbcTemplate;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

@ExtendWith(MockitoExtension.class)
public class EdiClientServiceTest {

    @Mock
    private EdiClientEntityDao ediClientEntityDao;

    @Mock
    private EdiClientEntityRepository ediClientEntityRepository;

    @InjectMocks
    private EdiClientService ediClientService;

    @Test
    @DisplayName("Test Find By Id Success")
    public void testFindByIdSuccess() {
        
    }

    @Test
    @DisplayName("Test Find By Id Fail")
    public void testFindByIdFail() {
        
    }

    @Test
    @DisplayName("Test Save Success")
    public void testSaveSuccess() {
        
    }

    @Test
    @DisplayName("Test Save Fail")
    public void testSaveFail() {
        
    }

    @Test
    @DisplayName("Test Save Client Null")
    public void testSaveClientNull() {
        
    }

    @Test
    @DisplayName("Test Save Client Id Null")
    public void testSaveClientIdNull() {
        
    }

    @Test
    @DisplayName("Test Save Client Created By Null")
    public void testSaveClientCreatedByNull() {
        
    }

    @Test
    @DisplayName("Test Save Client Updated By Null")
    public void testSaveClientUpdatedByNull() {
        
    }

    @Test
    @DisplayName("Test Save Client Created Date Null")
    public void testSaveClientCreatedDateNull() {
        
    }

    @Test
    @DisplayName("Test Save Client Updated Date Null")
    public void testSaveClientUpdatedDateNull() {
        
    }

    @Test
    @DisplayName("Test Save Client Status Null")
    public void testSaveClientStatusNull() {
        
    }

    @Test
    @DisplayName("Test Save Client Name Null")
    public void testSaveClientNameNull() {
        
    }

    @Test
    @DisplayName("Test Save Client Description Null")
    public void testSaveClientDescriptionNull() {
        
    }

    @Test
    @DisplayName("Test Save Client Alias Null")
    public void testSaveClientAliasNull() {
        
    }

    @Test
    @DisplayName("Test Save Client Trading As Null")
    public void testSaveClientTradingAsNull() {
        
    }

    @Test
    @DisplayName("Test Save Client Contact No Null")
    public void testSaveClientContactNoNull() {
        
    }

    @Test
    @DisplayName("Test Save Client Contact Email Null")
    public void testSaveClientContactEmailNull() {
        
    }

    @Test
    @DisplayName("Test Save Client Address Null")
    public void testSaveClientAddressNull() {
        
    }

    @Test
    @DisplayName("Test Save Client Edi Systems Null")
    public void testSaveClientEdiSystemsNull() {
        
    }

    @Test
    @DisplayName("Test Remove Success")
    public void testRemoveSuccess() {
        
    }

    @Test
    @DisplayName("Test Remove Fail")
    public void testRemoveFail() {
        
    }

    @Test
    @DisplayName("Test Get All Success")
    public void testGetAllSuccess() {
        
    }

    @Test
    @DisplayName("Test Get All Fail")
    public void testGetAllFail() {
        
    }

    @Test
    @DisplayName("Test Search Success")
    public void testSearchSuccess() {
        
    }

    @Test
    @DisplayName("Test Search Fail")
    public void testSearchFail() {
        
    }

    @Test
    @DisplayName("Test Find All By Id Success")
    public void testFindAllByIdSuccess() {
        
    }

    @Test
    @DisplayName("Test Find All By Id Fail")
    public void testFindAllByIdFail() {
        
    }

}