// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringService.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.roguesystems.edi.system;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContext;
import org.springframework.jdbc.core.JdbcTemplate;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

@ExtendWith(MockitoExtension.class)
public class EdiSystemServiceTest {

    @Mock
    private EdiSystemEntityDao ediSystemEntityDao;

    @Mock
    private EdiSystemEntityRepository ediSystemEntityRepository;

    @InjectMocks
    private EdiSystemService ediSystemService;

    @Test
    @DisplayName("Test Find By Id Success")
    public void testFindByIdSuccess() {
        
    }

    @Test
    @DisplayName("Test Find By Id Fail")
    public void testFindByIdFail() {
        
    }

    @Test
    @DisplayName("Test Save Success")
    public void testSaveSuccess() {
        
    }

    @Test
    @DisplayName("Test Save Fail")
    public void testSaveFail() {
        
    }

    @Test
    @DisplayName("Test Save Edi System Null")
    public void testSaveEdiSystemNull() {
        
    }

    @Test
    @DisplayName("Test Save Edi System Created By Null")
    public void testSaveEdiSystemCreatedByNull() {
        
    }

    @Test
    @DisplayName("Test Save Edi System Updated By Null")
    public void testSaveEdiSystemUpdatedByNull() {
        
    }

    @Test
    @DisplayName("Test Save Edi System Created Date Null")
    public void testSaveEdiSystemCreatedDateNull() {
        
    }

    @Test
    @DisplayName("Test Save Edi System Updated Date Null")
    public void testSaveEdiSystemUpdatedDateNull() {
        
    }

    @Test
    @DisplayName("Test Save Edi System Name Null")
    public void testSaveEdiSystemNameNull() {
        
    }

    @Test
    @DisplayName("Test Save Edi System Url Null")
    public void testSaveEdiSystemUrlNull() {
        
    }

    @Test
    @DisplayName("Test Save Edi System Description Null")
    public void testSaveEdiSystemDescriptionNull() {
        
    }

    @Test
    @DisplayName("Test Save Edi System Id Null")
    public void testSaveEdiSystemIdNull() {
        
    }

    @Test
    @DisplayName("Test Save Edi System Edi Client Null")
    public void testSaveEdiSystemEdiClientNull() {
        
    }

    @Test
    @DisplayName("Test Save Edi System System Components Null")
    public void testSaveEdiSystemSystemComponentsNull() {
        
    }

    @Test
    @DisplayName("Test Remove Success")
    public void testRemoveSuccess() {
        
    }

    @Test
    @DisplayName("Test Remove Fail")
    public void testRemoveFail() {
        
    }

    @Test
    @DisplayName("Test Get All Success")
    public void testGetAllSuccess() {
        
    }

    @Test
    @DisplayName("Test Get All Fail")
    public void testGetAllFail() {
        
    }

    @Test
    @DisplayName("Test Search Success")
    public void testSearchSuccess() {
        
    }

    @Test
    @DisplayName("Test Search Fail")
    public void testSearchFail() {
        
    }

    @Test
    @DisplayName("Test Search Criteria Null")
    public void testSearchCriteriaNull() {
        
    }

}