<!-- Generated by andromda-jakarta cartridge (views\jsp\403.jsp.vsl) DO NOT EDIT! -->
<%request.getSession().invalidate();%>
<%response.sendRedirect(request.getContextPath() + "/bw/co/roguesystems/dms/document.html?action=roleError");%>