<!-- Generated by andromda-jakarta cartridge (views\jsp\index.jsp.vsl) DO NOT EDIT! -->
<%response.sendRedirect(request.getContextPath() + "/app/bw/co/roguesystems/dms/document"+(request.getQueryString() != null ? "?"+request.getQueryString() : ""));%>
