server:
    port: 8090
    servlet:
        context-path: /rogueedi
spring:
    thymeleaf:
        cache: false
    mvc:
        format:
            date: iso
            date-time: iso
            time: HH:mm:ss
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    application:
        name: Rogue EDI
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: https://keycloak.roguedev.local/realms/rogueedi
                    jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs