// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on $springUtils.date.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.co.roguesystems.edi.system;

import bw.co.roguesystems.edi.site.SiteEntityRepository;
import org.springframework.stereotype.Repository;

/**
 * @see EdiSystemEntity
 */
@Repository("ediSystemEntityDao")
public class EdiSystemEntityDaoImpl
    extends EdiSystemEntityDaoBase
{
    
    public EdiSystemEntityDaoImpl(
        SiteEntityRepository siteEntityRepository,
        EdiSystemEntityRepository ediSystemEntityRepository
    ) {

        super(
            siteEntityRepository,
            ediSystemEntityRepository
        );
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void toEdiSystem(
        EdiSystemEntity source,
        EdiSystem target)
    {
        // TODO verify behavior of toEdiSystem
        super.toEdiSystem(source, target);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EdiSystem toEdiSystem(final EdiSystemEntity entity)
    {
        // TODO verify behavior of toEdiSystem
        return super.toEdiSystem(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private EdiSystemEntity loadEdiSystemEntityFromEdiSystem(EdiSystem ediSystem)
    {
        // TODO implement loadEdiSystemEntityFromEdiSystem
        throw new UnsupportedOperationException("bw.co.roguesystems.edi.system.loadEdiSystemEntityFromEdiSystem(EdiSystem) not yet implemented.");

        /* A typical implementation looks like this:
        if (ediSystem.getId() == null)
        {
            return  EdiSystemEntity.Factory.newInstance();
        }
        else
        {
            return this.load(ediSystem.getId());
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public EdiSystemEntity ediSystemToEntity(EdiSystem ediSystem)
    {
        // TODO verify behavior of ediSystemToEntity
        EdiSystemEntity entity = this.loadEdiSystemEntityFromEdiSystem(ediSystem);
        this.ediSystemToEntity(ediSystem, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void ediSystemToEntity(
        EdiSystem source,
        EdiSystemEntity target,
        boolean copyIfNull)
    {
        // TODO verify behavior of ediSystemToEntity
        super.ediSystemToEntity(source, target, copyIfNull);
    }
}