// license-header java merge-point
// Generated by andromda-thymeleaf cartridge (controllers\ControllerImpl.java.vsl)
package bw.co.roguesystems.edi.site;

import java.time.LocalDateTime;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * @see bw.co.roguesystems.edi.site.SiteController
 */
@Controller
@RequestMapping("/site")
public class SiteControllerImpl
    extends SiteControllerBase
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -4117208881053986054L;

    public SiteControllerImpl(SiteService siteService) {
        
        super(
            siteService        );
    }

    /**
     * @see bw.co.roguesystems.edi.site.SiteController#doInitialiseEditScreen(java.lang.Long id, Site site)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form, Model model)
    {
        // populating value with dummy instance
        Site site = new Site();
        site.setId(3355l);
        site.setCreatedBy(null);
        site.setUpdatedBy(null);
        site.setCreatedDate(null);
        site.setUpdatedDate(null);
        site.setName(null);
        site.setDescription(null);
        form.setSite(site);

        EditSiteForm frm = getEditSiteForm();
        model.addAttribute("editSiteForm", form); 
        
    }

    /**
     * @see bw.co.roguesystems.edi.site.SiteController#doDelete(Site site)
     */
    @Override
    public void doDelete(DoDeleteForm form, Model model)
    {
        // populating value with dummy instance
        Site site = new Site();
        site.setId(3355l);
        site.setCreatedBy(null);
        site.setUpdatedBy(null);
        site.setCreatedDate(null);
        site.setUpdatedDate(null);
        site.setName(null);
        site.setDescription(null);
        form.setSite(site);
    }

    /**
     * @see bw.co.roguesystems.edi.site.SiteController#doSave(Site site)
     */
    @Override
    public void doSave(DoSaveForm form, Model model)
    {
        // populating value with dummy instance
        Site site = new Site();
        site.setId(3355l);
        site.setCreatedBy(null);
        site.setUpdatedBy(null);
        site.setCreatedDate(null);
        site.setUpdatedDate(null);
        site.setName(null);
        site.setDescription(null);
        form.setSite(site);
    }

    /**
     * @see bw.co.roguesystems.edi.site.SiteController#doInitialiseSearchScreen()
     */
    @Override
    public void doInitialiseSearchScreen(Model model)
    {
    }

    /**
     * @see bw.co.roguesystems.edi.site.SiteController#doSearch(java.lang.String criteria)
     */
    @Override
    public void doSearch(DoSearchForm form, Model model)
    {
    }

    /**
     * @see bw.co.roguesystems.edi.site.SiteController#doEditGroup(java.lang.Long id)
     */
    @Override
    public void doEditGroup(DoEditGroupForm form, Model model)
    {
    }

    /**
     * This dummy variable is used to populate the "sites" table.
     * You may delete it when you add you own code in this controller.
     */
    private static final Site[] sites =
        new Site[]
        {
            new Site(null, "createdBy-1", "updatedBy-1", LocalDateTime.now(), LocalDateTime.now(), "name-1", "description-1"),
            new Site(null, "createdBy-2", "updatedBy-2", LocalDateTime.now(), LocalDateTime.now(), "name-2", "description-2"),
            new Site(null, "createdBy-3", "updatedBy-3", LocalDateTime.now(), LocalDateTime.now(), "name-3", "description-3"),
            new Site(null, "createdBy-4", "updatedBy-4", LocalDateTime.now(), LocalDateTime.now(), "name-4", "description-4"),
            new Site(null, "createdBy-5", "updatedBy-5", LocalDateTime.now(), LocalDateTime.now(), "name-5", "description-5")
        };
}