// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by SpringService.vsl in andromda-spring-cartridge on $springUtils.date. Do not modify by hand!.
//
package bw.co.roguesystems.edi.claim.submission;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContext;
import org.springframework.jdbc.core.JdbcTemplate;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;

@ExtendWith(MockitoExtension.class)
public class ClaimSubmissionServiceTest {

    @Mock
    private ClaimSubmissionEntityDao claimSubmissionEntityDao;

    @Mock
    private ClaimSubmissionEntityRepository claimSubmissionEntityRepository;

    @InjectMocks
    private ClaimSubmissionService claimSubmissionService;

    @Test
    @DisplayName("Test Find By Id Success")
    public void testFindByIdSuccess() {
        
    }

    @Test
    @DisplayName("Test Find By Id Fail")
    public void testFindByIdFail() {
        
    }

    @Test
    @DisplayName("Test Save Success")
    public void testSaveSuccess() {
        
    }

    @Test
    @DisplayName("Test Save Fail")
    public void testSaveFail() {
        
    }

    @Test
    @DisplayName("Test Save Claim Submission Null")
    public void testSaveClaimSubmissionNull() {
        
    }

    @Test
    @DisplayName("Test Save Claim Submission Id Null")
    public void testSaveClaimSubmissionIdNull() {
        
    }

    @Test
    @DisplayName("Test Save Claim Submission Status Null")
    public void testSaveClaimSubmissionStatusNull() {
        
    }

    @Test
    @DisplayName("Test Save Claim Submission Submission Date Null")
    public void testSaveClaimSubmissionSubmissionDateNull() {
        
    }

    @Test
    @DisplayName("Test Remove Success")
    public void testRemoveSuccess() {
        
    }

    @Test
    @DisplayName("Test Remove Fail")
    public void testRemoveFail() {
        
    }

    @Test
    @DisplayName("Test Get All Success")
    public void testGetAllSuccess() {
        
    }

    @Test
    @DisplayName("Test Get All Fail")
    public void testGetAllFail() {
        
    }

    @Test
    @DisplayName("Test Search Success")
    public void testSearchSuccess() {
        
    }

    @Test
    @DisplayName("Test Search Fail")
    public void testSearchFail() {
        
    }

    @Test
    @DisplayName("Test Find All By Id Success")
    public void testFindAllByIdSuccess() {
        
    }

    @Test
    @DisplayName("Test Find All By Id Fail")
    public void testFindAllByIdFail() {
        
    }

}