// license-header java merge-point
// Generated by andromda-thymeleaf cartridge (controllers\ControllerImpl.java.vsl)
package bw.co.roguesystems.edi.system;

import java.time.LocalDateTime;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * @see bw.co.roguesystems.edi.system.EdiSystemController
 */
@Controller
@RequestMapping("/system")
public class EdiSystemControllerImpl
    extends EdiSystemControllerBase
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -7248934575423928053L;

    public EdiSystemControllerImpl(EdiSystemService ediSystemService) {
        
        super(ediSystemService);
    }

    /**
     * @see bw.co.roguesystems.edi.system.EdiSystemController#doInitialiseEditScreen(java.lang.Long id, EdiSystem ediSystem)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form, Model model)
    {
        // populating value with dummy instance
        EdiSystem ediSystem = new EdiSystem();
        ediSystem.setCreatedBy(null);
        ediSystem.setUpdatedBy(null);
        ediSystem.setCreatedDate(null);
        ediSystem.setUpdatedDate(null);
        ediSystem.setName(null);
        ediSystem.setUrl(null);
        ediSystem.setDescription(null);
        ediSystem.setId(3355l); 
        form.setEdiSystem(ediSystem);
        
        EditEDISystemForm editEDISystemForm = getEditEDISystemForm();
        editEDISystemForm.setEdiSystem(ediSystem);
        model.addAttribute("editEDISystemForm", editEDISystemForm);

        System.out.println(1);
    }

    /**
     * @see bw.co.roguesystems.edi.system.EdiSystemController#doDelete(EdiSystem ediSystem)
     */
    @Override
    public void doDelete(DoDeleteForm form, Model model)
    {
        // populating value with dummy instance
        EdiSystem ediSystem = new EdiSystem();
        ediSystem.setCreatedBy(null);
        ediSystem.setUpdatedBy(null);
        ediSystem.setCreatedDate(null);
        ediSystem.setUpdatedDate(null);
        ediSystem.setName(null);
        ediSystem.setUrl(null);
        ediSystem.setDescription(null);
        ediSystem.setId(3355l);
        form.setEdiSystem(ediSystem);
        
        System.out.println(2);
    }

    /**
     * @see bw.co.roguesystems.edi.system.EdiSystemController#doSave(EdiSystem ediSystem)
     */
    @Override
    public void doSave(DoSaveForm form, Model model)
    {
        // populating value with dummy instance
        EdiSystem ediSystem = new EdiSystem();
        ediSystem.setCreatedBy(null);
        ediSystem.setUpdatedBy(null);
        ediSystem.setCreatedDate(null);
        ediSystem.setUpdatedDate(null);
        ediSystem.setName(null);
        ediSystem.setUrl(null);
        ediSystem.setDescription(null);
        ediSystem.setId(3355l);
        form.setEdiSystem(ediSystem);
        
        System.out.println(3);
    }

    /**
     * @see bw.co.roguesystems.edi.system.EdiSystemController#doInitialiseSearchScreen()
     */
    @Override
    public void doInitialiseSearchScreen(Model model)
    {
        SearchEDISystemsForm searchEDISystemsForm = getSearchEDISystemsForm();
        model.addAttribute("searchEDISystemsForm", searchEDISystemsForm);
        
    }

    /**
     * @see bw.co.roguesystems.edi.system.EdiSystemController#doSearch(java.lang.String criteria)
     */
    @Override
    public void doSearch(DoSearchForm form, Model model)
    {
        SearchEDISystemsForm searchEDISystemsForm = getSearchEDISystemsForm();
        model.addAttribute("searchEDISystemsForm", searchEDISystemsForm);
        System.out.println(5);
    }

    /**
     * @see bw.co.roguesystems.edi.system.EdiSystemController#doEditGroup(java.lang.Long id)
     */
    @Override
    public void doEditGroup(DoEditGroupForm form, Model model)
    {
        // SearchEDISystemsForm searchEDISystemsForm = getSearchEDISystemsForm();
        // model.addAttribute("searchEDISystemsForm", searchEDISystemsForm);
    }

    /**
     * This dummy variable is used to populate the "ediSystems" table.
     * You may delete it when you add you own code in this controller.
     */
    private static final EdiSystem[] ediSystems =
        new EdiSystem[]
        {
            new EdiSystem("createdBy-1", "updatedBy-1", LocalDateTime.now(), LocalDateTime.now(), "name-1", "url-1", "description-1", null),
            new EdiSystem("createdBy-2", "updatedBy-2", LocalDateTime.now(), LocalDateTime.now(), "name-2", "url-2", "description-2", null),
            new EdiSystem("createdBy-3", "updatedBy-3", LocalDateTime.now(), LocalDateTime.now(), "name-3", "url-3", "description-3", null),
            new EdiSystem("createdBy-4", "updatedBy-4", LocalDateTime.now(), LocalDateTime.now(), "name-4", "url-4", "description-4", null),
            new EdiSystem("createdBy-5", "updatedBy-5", LocalDateTime.now(), LocalDateTime.now(), "name-5", "url-5", "description-5", null)
        };
}